sudo: required

services:
  - docker

os:
  - linux

language: python
python:
  - "3.6"

install:
 - pip install coveralls
 - pip install -r requirements.txt

# To check how to build the docker image on ARM, read thid:
# https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/ 
script:
  - coverage run  --source app  -m unittest discover tests
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t juli1/flask-chat:rpi -f Dockerfile.rpi .
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push juli1/flask-chat:rpi

after_success:
    coveralls
